//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Лопушок
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материалы()
        {
            this.Материалы_продуктов = new HashSet<Материалы_продуктов>();
        }
    
        public int ИД { get; set; }
        public string Наименование { get; set; }
        public string Тип { get; set; }
        public int Количество_в_упаковке { get; set; }
        public string Еденица_измерения { get; set; }
        public int Количество_на_складе { get; set; }
        public int Минимальный_возможный_остаток { get; set; }
        public decimal Стоимость { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материалы_продуктов> Материалы_продуктов { get; set; }
    }
}
